# Site settings
title: Project GECKO
email: gecko@theprojectgecko.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "theprojectgecko.com" # the subpath of your site, e.g. /blog/
url: "theprojectgecko.com" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
